{% set name = "matscipy" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matscipy-{{ version }}.tar.gz
  sha256: 078dabf4574cd74c08789e956516dca94e3d49cd5f27f044418af36b7275a063

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - setuptools
    - numpy
    - pytest-runner
    - meson-python
  run:
    - python
    - ase
    - numpy
    - scipy

test:
  imports:
    - matscipy
    - matscipy.io
    - matscipy.tool
    - matscipy.fracture_mechanics
    - matscipy.contact_mechanics
    - matscipy.electrochemistry
    - matscipy.calculators
    - matscipy.calculators.eam
    - matscipy.calculators.pair_potential
    - matscipy.calculators.polydisperse
    - matscipy.calculators.mcfm
    - matscipy.calculators.mcfm.mcfm_parallel
    - matscipy.calculators.mcfm.neighbour_list_mcfm
    - matscipy.calculators.mcfm.qm_cluster_tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/libAtoms/matscipy
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Materials science with Python at the atomic-scale
  description: |
    This repository contains generic Python materials science tools built 
    around the Atomic Simulation Environment (ASE).
  doc_url: https://github.com/libAtoms/matscipy
  dev_url: https://github.com/libAtoms/matscipy

extra:
  recipe-maintainers:
    - jan-janssen
