{% set name = "matscipy" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matscipy-{{ version }}.tar.gz
  sha256: 2d806d27bfcb99c6e365e0e20cee08e71952ce37b5df3667a1b955dbe26138c2
  patches:
    - version.patch  # [linux]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - meson >=1.0.0
    - meson-python >=0.13.0
    - ninja
    - numpy
    - pip
  run:
    - python
    - numpy >=1.16.0
    - scipy >=1.2.3
    - ase >=3.16.0
    - looseversion

test:
  imports:
    - matscipy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/libAtoms/matscipy
  license: LGPL-2.1-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Materials science with Python at the atomic-scale
  description: |
    This repository contains generic Python materials science tools built 
    around the Atomic Simulation Environment (ASE).
  doc_url: https://github.com/libAtoms/matscipy
  dev_url: https://github.com/libAtoms/matscipy

extra:
  recipe-maintainers:
    - jan-janssen
